CREATE TABLE users (id INT PRIMARY KEY, name TEXT NOT NULL, email VARCHAR(255) NOT NULL);
CREATE TABLE posts (id INT PRIMARY KEY, user_id INT NOT NULL, title TEXT NOT NULL, body TEXT);
CREATE TABLE comments (id INT PRIMARY KEY, post_id INT NOT NULL, author TEXT NOT NULL);
CREATE TABLE tags (id INT PRIMARY KEY, label TEXT NOT NULL);
CREATE TABLE post_tags (post_id INT NOT NULL, tag_id INT NOT NULL);
