#! /bin/bash

set -e -u

sqlgg -gen cxx test.sql > test_cxx_gen.hpp
sqlgg -gen caml test.sql > test_caml_gen.ml

g++ -g -DSQLGG_DEBUG -o test_cxx test_cxx.cpp -lsqlite3

ocamlfind ocamlc -linkpkg -package sqlite3 -w Alse -g -o test_caml -I ../impl ../impl/sqlgg_sqlite3.ml ../impl/sqlgg_traits.ml test_caml_gen.ml test_caml.ml
