#! /bin/sh

set -e -u

mode=${1:-run}

if [ "$mode" = "init" ] ; then
  OUTDIR=test/out
  echo Initializing test outputs in $OUTDIR
else
  OUTDIR=test/tmp
  echo Running regression tests
fi

mkdir -p test/out test/tmp
for file in test/*.sql; do
  basename=${file#test/}
  _build/src/cli.native -no-header -params named -gen xml $file > $OUTDIR/${basename%.sql}.xml || { echo FAILED $file; exit 2; }
done

[ "$mode" = "init" ] || diff --strip-trailing-cr -u test/out test/tmp

echo OK
