#! /bin/sh

set -e -u

OUTDIR=test/out
echo Running regression tests

mkdir -p test/out
for file in test/*.sql; do
  basename=${file#test/}
  _build/src/cli.native -no-header -params named -gen xml "$file" > "$OUTDIR/${basename%.sql}.xml" || { echo "FAILED $file"; exit 2; }
done

if git diff --no-ext-diff --quiet --exit-code "$OUTDIR" ; then
  echo OK
else
  echo FAILED
  git status -uno -s "$OUTDIR"
  exit 2
fi
