#! /bin/bash

set -e -u

www=/home/ygrek/work/ygrek_web/ygrek.org.ua
sqlgg=$www/p/sqlgg

sed -e 's|sqlgg.cgi|/exec/sqlgg.cgi|' overview.md > $sqlgg/index.md
cp changelog $sqlgg/dist/changelog
cp -a impl/*.{hpp,ml} $sqlgg/impl/
cp -a demo/*.{cpp,hpp,ml,xml,java,cs} $sqlgg/demo/
make -C $www
svn add $sqlgg/{demo,impl,dist}/*
svn ci $www
