#! /bin/bash

set -e -u

sed -r 's/%([^%]*)%([^%]*)%/\1/' demo.sql.pp > demo_mysql.sql
sed -r 's/%([^%]*)%([^%]*)%/\2/' demo.sql.pp > demo_sqlite3.sql

sqlgg -gen cxx demo_sqlite3.sql > demo_cxx_gen.hpp
sqlgg -gen cxx -params unnamed demo_mysql.sql > demo_cxx_gen_mysql.hpp
sqlgg -gen caml demo_sqlite3.sql > demo_caml_gen.ml
sqlgg -gen caml -params unnamed demo_mysql.sql > demo_caml_gen_mysql.ml
sqlgg -gen xml demo_sqlite3.sql > demo_xml_gen.xml
sqlgg -gen java -name demo_java_gen demo_mysql.sql > demo_java_gen.java
sqlgg -gen csharp demo_mysql.sql > demo_csharp_gen.cs

g++ -Wall -DSQLGG_DEBUG -g -o demo_cxx demo_cxx.cpp -lsqlite3

ocamlfind ocamlc -linkpkg -package sqlite3 -w Alse -g -o demo_caml -I ../impl ../impl/sqlgg_sqlite3.ml ../impl/sqlgg_traits.ml demo_caml_gen.ml demo_caml.ml
# requires ocaml-mysql >= 1.1.0
ocamlfind ocamlc -linkpkg -package mysql -w Alse -g -o demo_caml_mysql -I ../impl ../impl/sqlgg_mysql.ml ../impl/sqlgg_traits.ml demo_caml_gen_mysql.ml demo_caml_mysql.ml

g++ -Wall -DSQLGG_DEBUG -g -o demo_cxx_mysql demo_cxx_mysql.cpp -lmysqlclient

javac demo_java.java

gmcs -r:System.Data -r:MySql.Data demo_csharp.cs demo_csharp_gen.cs

