#! /bin/bash

set -e -u

../sqlgg.byte -gen cxx demo.sql > demo_cxx_gen.hpp
g++ -g -o demo_cxx demo_cxx.cpp -lsqlite3

../sqlgg.byte -gen caml demo.sql > demo_caml_gen.ml
#ocamlc -w Ase ../impl/database.ml -i demo_caml_gen.ml > demo_caml_gen.i
ocamlc -w Alse -g -o demo_caml -I +sqlite3 -I ../impl sqlite3.cma ../impl/sqlgg_sqlite3.ml ../impl/sqlgg_traits.ml demo_caml_gen.ml demo_caml.ml
