open ExtLib
open Sqlgg

(** Exception with preserved backtrace *)
exception With_backtrace of exn * Printexc.raw_backtrace

let () = Printexc.(register_printer begin function
  | With_backtrace (exn,bt) when raw_backtrace_length bt = 0 -> Some (to_string exn)
  | With_backtrace (exn,bt) -> Some (Printf.sprintf "%s\nBacktrace:\n%s" (to_string exn) (raw_backtrace_to_string bt))
  | _ -> None
end)

let dynamic_select_mode props =
  match Props.dynamic_select props with
  | Some mode -> mode
  | None when !Sqlgg_config.dynamic_select -> Props.Both
  | None -> Props.Off

let check_dialect sql dialect_features =
  let open Dialect in
  let position_info ({ pos = (f, l); _ }: dialect_support) = String.slice ~first:f ~last:l sql in
  dialect_features |> List.iter (fun ds ->
    let skip = List.mem ds.feature !Sqlgg_config.no_check_features in
    match support ds !selected, skip with
    | `Supported, _ -> ()
    | `Unsupported, true ->
        Error.warn "%s, proceeding anyway at %s\n" (unsupported_message ~alternatives:false ds !selected) (position_info ds)
    | `Unsupported, false ->
        Error.log "%s at %s" (unsupported_message ds !selected) (position_info ds)
    | `Unknown, true ->
        (match ds.feature with
        | Collation ->
            Error.warn "Assuming custom collation implementation for %s\n"
              (show !selected)
        | _ ->
            Error.warn "%s at %s\n" (unknown_message ds !selected) (position_info ds))
    | `Unknown, false ->
        Error.log
          "Unknown dialect support for feature %s with dialect %s at %s, use -no-check=all to skip all checks or -no-check=%s to skip this feature check"
          (show_feature ds.feature) (show !selected) (position_info ds) (feature_to_string ds.feature))

let of_syntax props ({ sql; schema; vars; kind; dialect_features; _ } : Syntax.result) =
  check_dialect sql dialect_features;
  begin match kind, !Gen.params_mode with
  | Stmt.Insert (Some _, _), None -> Error.log "Cannot use `-params none` with autogenerated parameters"
  | _ -> ()
  end;
  { Gen.schema; vars; kind; props = Props.Sql sql :: props }

let compile ~dynamic_select (stmt : Statements.t) =
  let sql = stmt.text in
  if Sqlgg_config.debug1 () then Printf.eprintf "------\n%s\n%!" sql;
  try
    Some (Compile.statement ~dynamic_select stmt)
  with
  | Parser_utils.Error (exn, { pos = (_, stop); token; tail }) ->
    let extra = Parser_utils.message_of_exn exn in
    Error.log "==> %s" sql;
    if stop = String.length sql && token = "" then
      Error.log "Error: %s" extra
    else begin
      let (line, col) = Line_index.position (Line_index.make sql) stop in
      Error.log "Position %u:%u Tokens: %s%s\nError: %s" (line + 1) col token (String.sub tail 0 (Int.min 32 (String.length tail))) extra
    end;
    None
  | exn ->
    let bt = Printexc.get_raw_backtrace () in
    Error.log "Failed %s: %s" (Stdlib.Option.value ~default:"" (Props.name stmt.props)) sql;
    let exn =
      match exn with
      | Prelude.At ((p1, p2), exn) -> Error.log "At : %s" (String.sub sql p1 (p2 - p1)); exn
      | _ -> exn
    in
    raise @@ With_backtrace (exn, bt)

let executable (stmt : Statements.t) =
  match compile ~dynamic_select:(dynamic_select_mode stmt.props) stmt with
  | Some (Compile.Executable syntax) -> Some (of_syntax stmt.props syntax)
  | Some (Compile.Verbatim | Compile.Reusable _ | Compile.Not_reusable) | None -> None

let parse_one (stmt : Statements.t) =
  let sql = stmt.text and props = stmt.props in
  let mode = dynamic_select_mode props in
  match compile ~dynamic_select:mode stmt with
  | None -> []
  | Some Compile.Verbatim ->
    [ { Gen.schema = []; vars = []; kind = Stmt.Other; props = Props.Sql sql :: props } ]
  | Some Compile.Not_reusable ->
    if Sqlgg_config.debug1 () then Error.log "Cannot use shared with non-select statement";
    []
  | Some (Compile.Reusable { dialect_features; _ }) ->
    check_dialect sql dialect_features;
    []
  | Some (Compile.Executable syntax) ->
    let gen = of_syntax props syntax in
    let has_dynamic_select = List.exists (function Sql.DynamicSelect _ -> true | _ -> false) gen.vars in
    let only_executable = match Props.include_ props with Execute -> true | Reuse | Reuse_and_execute -> false in
    if has_dynamic_select && only_executable && mode = Props.Both then
      let props = Props.Dynamic_select Off :: props in
      let props =
        match Props.name props with
        | Some name -> Props.Name (name ^ "_static") :: props
        | None -> props
      in
      match executable { stmt with props } with
      | Some static -> [ gen; static ]
      | None -> [ gen ]
    else [ gen ]

let statements text =
  Statements.split text
  |> List.filter (fun (stmt : Statements.t) ->
    match stmt.errors with
    | [] -> true
    | ((start, stop), msg) :: _ -> Error.log "%s at %d-%d" msg start stop; false)
  |> List.map (fun (stmt : Statements.t) ->
    let gaps =
      let (starts, stops) = List.split stmt.comments in
      List.combine (0 :: stops) (starts @ [ String.length stmt.text ])
    in
    let removed_before offset =
      List.fold_left (fun n (start, stop) -> if stop <= offset then n + stop - start else n) 0 stmt.comments
    in
    { stmt with
      text = String.concat "" (List.map (fun (start, stop) -> String.sub stmt.text start (stop - start)) gaps);
      metadata = List.map (fun (offset, props) -> offset - removed_before offset, props) stmt.metadata;
      comments = [] })

let get_statements ch =
  statements (In_channel.input_all ch)
  |> List.concat_map (fun (stmt : Statements.t) ->
    match parse_one stmt with
    | [] -> []
    | first :: _ as stmts ->
      if not (Sql.Schema.is_unique (Sql.schema_of_columns first.Gen.schema)) then
        Printf.eprintf "Warning: this SQL statement will produce rowset with duplicate column names:\n%s\n" stmt.text;
      stmts)

let replay_statement stmt = ignore (executable stmt)

let replay_sql sql = List.iter replay_statement (statements sql)

let raw_blocks ch = Statements.glue_downs (statements (In_channel.input_all ch))

let migration_of_block (block : Statements.t) =
  executable block |> Option.map (fun (stmt : Gen.stmt) ->
    let apply = String.trim block.text in
    let revert =
      match Props.has Irreversible block.props, Props.down block.props with
      | true, _ -> []
      | false, Some d -> [d]
      | false, None -> Error.log "migration has no `down`:\n%s" apply; [""]
    in
    let props =
      match Props.name stmt.props, Props.id block.props with
      | None, Some raw ->
        (match Migration_id.parse raw with
         | Some id when Option.is_some (Migration_id.name id) ->
           Props.Name (Migration_id.to_string id) :: stmt.props
         | _ -> stmt.props)
      | _ -> stmt.props
    in
    { Gen_migrations.props; kind = stmt.kind; apply = [apply]; revert })

let with_channel filename f =
  match try Some (open_in filename) with _ -> None with
  | None -> Error.log "cannot open file : %s" filename; f None
  | Some ch -> Std.finally (fun () -> close_in_noerr ch) f (Some ch)
