open ExtLib
open Sqlgg

module L = List
module S = String

(** Exception with preserved backtrace *)
exception With_backtrace of exn * Printexc.raw_backtrace

let () = Printexc.(register_printer begin function
  | With_backtrace (exn,bt) when raw_backtrace_length bt = 0 -> Some (to_string exn)
  | With_backtrace (exn,bt) -> Some (Printf.sprintf "%s\nBacktrace:\n%s" (to_string exn) (raw_backtrace_to_string bt))
  | _ -> None
end)

type dynamic_select_mode = Dynamic_off | Dynamic_only | Dynamic_both [@@deriving eq]

let dynamic_select_mode props =
  match Props.get props "dynamic_select" with
  | None -> if !Sqlgg_config.dynamic_select then Dynamic_both else Dynamic_off
  | Some s ->
    match String.lowercase_ascii s with
    | "true" -> Dynamic_only
    | "both" -> Dynamic_both
    | "false" -> Dynamic_off
    | other ->
      Error.log "Unknown dynamic_select=%s (expected true, both or false)" other;
      Dynamic_off

(** Handle parsing error and format a helpful error message *)
let handle_parsing_error sql exn (line, cnum, tok, tail) =
  let extra = match exn with
    | Sql.Schema.Error (_, msg) -> msg
    | exn -> Printexc.to_string exn
  in
  Error.log "==> %s" sql;
  if cnum = String.length sql && tok = "" then
    Error.log "Error: %s" extra
  else
    Error.log "Position %u:%u Tokens: %s%s\nError: %s" line cnum tok (String.slice ~last:32 tail) extra;
  None

let preserve_exception_context sql props exn =
  let bt = Printexc.get_raw_backtrace () in
  Error.log "Failed %s: %s" (Option.default "" @@ Props.get props "name") sql;
  let exn =
    match exn with
    | Prelude.At ((p1, p2), exn) -> 
        Error.log "At : %s" (String.slice ~first:p1 ~last:p2 sql); 
        exn
    | _ -> exn
  in
  raise @@ With_backtrace (exn, bt)


let check_dialect sql dialect_features =
  let open Dialect in
  let check_support_for_dialect ds selected_dialect =
    let { supported; unsupported; _ } = ds.state in
    if List.mem selected_dialect supported then `Supported
    else if List.mem selected_dialect unsupported then `Unsupported
    else `Unknown
  in
  let position_info ({ pos = (f, l); _ }: dialect_support) = String.slice ~first:f ~last:l sql in
  dialect_features |> List.iter (fun ds ->
    let skip = List.mem ds.feature !Sqlgg_config.no_check_features in
    match check_support_for_dialect ds !selected, skip with
    | `Supported, _ -> ()
    | `Unsupported, true ->
        Error.warn "Feature %s is not supported for dialect %s, proceeding anyway at %s\n"
          (show_feature ds.feature) (show !selected) (position_info ds)
    | `Unsupported, false ->
        let supported_dialects = String.concat ", " (List.map show ds.state.supported) in
        let supported_info =
          if ds.state.supported = [] then ""
          else Printf.sprintf " (supported by: %s)" supported_dialects
        in
        Error.log "Feature %s is not supported for dialect %s%s at %s"
          (show_feature ds.feature) (show !selected) supported_info
          (position_info ds)
    | `Unknown, true ->
        (match ds.feature with
        | Collation ->
            Error.warn "Assuming custom collation implementation for %s\n"
              (show !selected)
        | _ ->
            Error.warn
              "Feature %s has unknown support for dialect %s at %s\n"
              (show_feature ds.feature) (show !selected) (position_info ds))
    | `Unknown, false ->
        Error.log
          "Unknown dialect support for feature %s with dialect %s at %s, use -no-check=all to skip all checks or -no-check=%s to skip this feature check"
          (show_feature ds.feature) (show !selected) (position_info ds) (feature_to_string ds.feature))

let check_statement stmt sql =
  let schema = List.concat_map (function
    | Sql.Attr attr -> [attr]
    | Dynamic (_, l) -> List.map (fun f -> f.Sql.field_attr) l) stmt.Gen.schema in
  if not (Sql.Schema.is_unique schema) then
    Printf.eprintf "Warning: this SQL statement will produce rowset with duplicate column names:\n%s\n" sql;
  match stmt.kind with
  | Insert (Some _, _) when !Gen.params_mode = None ->
    Error.log "Cannot use `-params none` with autogenerated parameters"
  | _ -> ()

let parse_one' (sql, props) =
    if Sqlgg_config.debug1 () then Printf.eprintf "------\n%s\n%!" sql;
    Syntax.Config.dynamic_select := not (equal_dynamic_select_mode (dynamic_select_mode props) Dynamic_off);
    let (sql, schema, vars, kind, dialect_features) = Syntax.parse sql in
    check_dialect sql dialect_features;
    begin match kind, !Gen.params_mode with
    | Insert (Some _, _), None -> Error.log "Cannot use `-params none` with autogenerated parameters"
    | _ -> ()
    end;
    let props = Props.set props "sql" sql in
    { Gen.schema; vars; kind; props; src = None }

(** @return parsed statement or [None] in case of parsing failure.
    @raise exn for other errors (typing etc)
*)
let try_parse f (sql, props as x) =
  try
    Some (f x)
  with
  | Parser_utils.Error (exn, (line, cnum, tok, tail)) ->
      handle_parsing_error sql exn (line, cnum, tok, tail)
  | exn ->
      preserve_exception_context sql props exn

let stmt_has_dynamic_select (stmt : Gen.stmt) =
  List.exists (function Sql.DynamicSelect _ -> true | _ -> false) stmt.vars

let parse_one (sql, props as x) =
  match Props.get props "noparse" with
  | Some _ -> [ { Gen.schema=[]; vars=[]; kind=Stmt.Other; props=Props.set props "sql" sql; src=None } ]
  | None ->
    match try_parse parse_one' x with
    | None -> []
    | Some stmt when stmt_has_dynamic_select stmt && equal_dynamic_select_mode (dynamic_select_mode props) Dynamic_both ->
      let static_props =
        let props = Props.set props "dynamic_select" "false" in
        match Props.get props "name" with
        | Some name -> Props.set props "name" (name ^ "_static")
        | None -> props
      in
      begin match try_parse parse_one' (sql, static_props) with
      | Some static_stmt -> [stmt; static_stmt]
      | None -> [stmt]
      end
    | Some stmt -> [stmt]

(** Parse a select statement for sharing *)
let parse_select_one (sql, props) =
  try
    match Parser.parse_stmt sql with
    | { statement=Select select_full; dialect_features } -> 
        check_dialect sql dialect_features;
        Shared_queries.add (Option.default "" (Props.get props "name")) (sql, select_full); 
        Some select_full
    | _ -> 
        if Sqlgg_config.debug1 () then 
          Error.log "Cannot use shared with non-select statement";
        None
  with
  | Parser_utils.Error (exn, (line, cnum, tok, tail)) ->
      handle_parsing_error sql exn (line, cnum, tok, tail)
  | exn ->
      preserve_exception_context sql props exn

type token = [
  | `Comment of string 
  | `Token of string 
  | `Char of char
  | `Space of string 
  | `Semicolon 
  | `Props of (string * string) list
]

module Include = struct
  type t = OnlyReusable | OnlyExecutable | ReusableAndExecutable

  let of_string = function
    | "reuse" -> OnlyReusable
    | "execute" -> OnlyExecutable
    | "reuse_and_execute"-> ReusableAndExecutable
    | s -> failwith @@ Printf.sprintf "Unknown include option %s" s

  let of_string_opt s = try (Some (of_string s))
    with Failure _ -> None
end

let lex_tokens lexbuf =
  Enum.from (fun () ->
    match Sql_lexer.ruleStatement lexbuf with
    | `Eof -> raise Enum.No_more_elements
    | #token as x -> (x, Lexing.lexeme_start lexbuf))

let lex_channel ch =
  let source = Std.input_all ch in
  let line = Array.make (String.length source + 1) 1 in
  String.iteri (fun i c -> line.(i + 1) <- line.(i) + (if c = '\n' then 1 else 0)) source;
  lex_tokens (Lexing.from_string source), Array.get line

let extract_statement' tokens =
    let b = Buffer.create 1024 in
    let props = ref Props.empty in
    let answer start = Buffer.contents b, !props, start in

    let internal_props = ref Props.empty in

    let flush_internal_props () =
      if !internal_props <> Props.empty then (
        Parser_state.Stmt_metadata.add (Buffer.length b) !internal_props;
        internal_props := Props.empty;
      )
    in

    let rec loop start =
      let started = Option.is_some start in
      match Enum.get tokens with
      | None -> if started then Some (answer start) else None
      | Some (x, off) ->
        let content_start = if started then start else Some off in
        begin match x with
        | `Comment _ -> loop start
        | `Char c -> flush_internal_props (); Buffer.add_char b c; loop content_start
        | `Token s -> flush_internal_props (); Buffer.add_string b s; loop content_start
        | `Space _ when not started -> loop start
        | `Space s -> Buffer.add_string b s; loop start
        | `Props p when started -> internal_props := Props.set_all p !internal_props; loop start
        | `Props p -> props := Props.set_all p !props; loop start
        | `Semicolon -> Some (answer start)
        end
    in
    Parser_state.Stmt_metadata.reset();
    try loop None
    with e -> 
      Error.log "lexer failed (%s)" (Printexc.to_string e); 
      None

let get_statements ?file ch =
  let (tokens, line_at) = lex_channel ch in
  Enum.from (fun () ->
    match extract_statement' tokens with
    | Some x -> x
    | None -> raise Enum.No_more_elements)
  |> Enum.map (fun (buffer, props, start) ->
    let props = Option.map_default (Props.set props "file") props file in
    let src = match file, start with
      | Some file, Some off -> Some { Gen.file; line = line_at off }
      | _ -> None
    in
    let include_ = match Props.get props "include" with
      | Some s -> Include.of_string s
      | None -> Include.OnlyExecutable
    in
    List.map (fun (stmt : Gen.stmt) -> { stmt with Gen.src }) @@
    match include_ with
    | OnlyReusable ->
      let (_: Sql.select_full option) = parse_select_one (buffer, props) in
      []
    | OnlyExecutable ->
      begin match parse_one (buffer, props) with
      | [] -> []
      | stmt :: _ as stmts -> check_statement stmt buffer; stmts
      end
    | ReusableAndExecutable ->
      parse_select_one (buffer, props) |> Option.map_default (fun select_full ->
        let (schema, vars, kind) = Syntax.eval_select select_full in
        let stmt = { Gen.schema; vars; kind; props = Props.set props "sql" buffer; src = None } in
        check_statement stmt buffer; [stmt]) []
  ) |> List.of_enum |> List.concat

let replay_sql sql = ignore (try_parse parse_one' (sql, Props.empty))

let collect_blocks ch =
  let (tokens, line_at) = lex_channel ch in
  let rec aux acc =
    match extract_statement' tokens with
    | None -> List.rev acc
    | Some (buffer, props, start) ->
      let b = String.trim buffer in
      if b = "" then aux acc else
      let props =
        Option.map_default (fun off -> Props.set props "line" (string_of_int (line_at off))) props start
      in
      aux ((b, props) :: acc)
  in
  aux []

let glue_downs blocks =
  let has prop props = Props.get props prop <> None in
  let rec aux = function
    | (sql, props) :: (down_sql, down_props) :: rest
      when has "id" props && not (has "down" props) && not (has "irreversible" props)
           && not (has "id" down_props) ->
      let props = Option.map_default (Props.set props "down_line") props (Props.get down_props "line") in
      (sql, Props.set props "down" down_sql) :: aux rest
    | b :: rest -> b :: aux rest
    | [] -> []
  in
  aux blocks

let raw_blocks ch = glue_downs (collect_blocks ch)

let replay_schema ch =
  collect_blocks ch
  |> glue_downs
  |> List.iter (fun (sql, props) ->
    match Props.get props "noparse" with
    | Some _ -> ()
    | None -> ignore (try_parse parse_one' (sql, props)))

let migration_of_block (sql, props) =
  try_parse parse_one' (sql, props) |> Option.map (fun (stmt : Gen.stmt) ->
    let apply = String.trim sql in
    let revert =
      match Props.get props "irreversible", Props.get props "down" with
      | Some _, _ -> []
      | None, Some d -> [d]
      | None, None -> Error.log "migration has no `down`:\n%s" apply; [""]
    in
    let props =
      match Props.get stmt.props "name", Props.get props "id" with
      | None, Some raw ->
        (match Migration_id.parse raw with
         | Some id when Option.is_some (Migration_id.name id) ->
           Props.set stmt.props "name" (Migration_id.to_string id)
         | _ -> stmt.props)
      | _ -> stmt.props
    in
    let src key =
      match Props.get props "file", Props.get props key with
      | Some file, Some line -> Option.map (fun line -> { Gen.file; line }) (int_of_string_opt line)
      | _ -> None
    in
    { Gen_migrations.props; kind = stmt.kind; apply = [apply]; revert;
      apply_src = src "line"; revert_src = src "down_line" })

let with_channel filename f =
  match try Some (open_in filename) with _ -> None with
  | None -> Error.log "cannot open file : %s" filename; f None
  | Some ch -> Std.finally (fun () -> close_in_noerr ch) f (Some ch)
