
CREATE TABLE t1 (x INT, y INT, z TEXT);
CREATE TABLE t2 (a INT, b INT, c INT);
CREATE TABLE t3 (a INT, b INT);

SELECT * FROM t1 UNION SELECT * FROM t2;
SELECT * FROM t1 UNION SELECT * FROM t3;
SELECT * FROM t1 UNION SELECT 1,2,3;

SELECT FROM t1;

